### ISSUE TITLE
Pokeplayer moves not working

### ISSUE THREAD

**Issue by Greenjoe12345** [Thutmose/Pokeplayer#8]
using moves as pokeplayer does not seem to be working
using a close range move does not work at all, while a ranged move just drops

aiming at a pokemon says 'You tell (your username) to use (the move)' and does nothing, except for angering the enemy mon sometimes
or 'You tell (your username) to attack (target)'
move is not used in those situations
https://imgur.com/a/3jkuL
Here's some of the messages

**Comment by ParasiticSquid** [comment]
Im having the exact same problem. Thought it was a mod incompatibility at first but after loads of testing turns out it's just a bug with pokeplayer at the moment.

Hopefully it gets fixed soon since without moves there's little point to pokeplayer except cosmetic/roleplay purposes. Can't even level up without moves since exp is only gained when killing any pokemon or a normal/modded mob( even when non-pokemob exp is set to true ) with a pokecube move

**Comment by Greenjoe12345** [comment]
Update: this is somewhat fixed, made a new issue, now it only works when aimed at a mob
